language: bash
sudo: required
services:
  - docker

script:
  - docker info
  - df -h
  - ls -lha /tmp && ls -lha /tmp/led-blink
  - cp -r ./baseos/examples/led-blink /tmp/led-blink
  - ls -lha /tmp && ls -lha /tmp/led-blink
  - docker run -t -v /tmp/led-blink:/app codestand/baseos
  - rm -r /tmp/led-blink
  - ls -lha /tmp && ls -lha /tmp/led-blink
  - sudo mount -t tmpfs tmpfs /tmp
  - ls -lha /tmp && ls -lha /tmp/led-blink
  - cp -r ./baseos/examples/led-blink /tmp/led-blink
  - ls -lha /tmp && ls -lha /tmp/led-blink
  - docker run -t -v /tmp/led-blink:/app codestand/baseos
