language: cpp
compiler:
  - gcc
script:
  - sudo add-apt-repository -y ppa:serge-hallyn/crossc
  - sudo apt-get -y update
  - sudo apt-get install binutils-sparc-cross
  - sudo apt-get install gcc-4.7-sparc-cross
