language: bash

git:
  depth: 1
  submodules: false

sudo: required # to run docker

services:
  - docker

env:  
  global:
    - DOCKER_VERSION=1.11.2
    - DOCKER_COMPOSE_VERSION=1.7.1

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=$(apt-cache madison docker-engine | grep ${DOCKER_VERSION} | head -n 1 | awk '{print $3}')

  # reinstall docker-compose at specific version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - bash script/convert.bash

script:
  - sudo docker-compose build
