language: c

sudo: false

install:
  - echo hello
  - ls /home/travis
  - if [ -f /home/travis/foo/bar/hello.txt ]; then stat /home/travis/foo/bar/hello.txt | grep Modify; fi

script:
  - echo world
  - mkdir -p /home/travis/foo/bar
  - date +"%s" > /home/travis/foo/bar/hello.txt
  - touch -mt 200904101015 /home/travis/foo/bar/hello.txt
  - stat /home/travis/foo/bar/hello.txt | grep Modify;

cache:
  directories:
    - /home/travis/foo/bar

