language: bash
sudo: required
services:
- mysql
before_install:
- ls /var/run/mysqld
- mysql -uroot -e 'create database hello1;';
- mysql -u root -e 'create database hello2;';
script:
- ls /var/run/mysqld
- mysql -uroot -e 'create database hello3;';
- mysql -u root -e 'create database hello4;';
- mysql -e 'create datbase hello;'
