language: ruby

sudo: false

install:
  - echo hello
  - if [ -f $HOME/tmp/hello.txt ]; then stat $HOME/tmp/hello.txt | grep Modify; fi

script:
  - echo world
  - mkdir -p $HOME/foo/bar
  - touch -mt 200904101015 $HOME/foo/bar/hello.txt
  - stat $HOME/foo/bar/hello.txt | grep Modify;

cache:
  directories:
    - $HOME/foo/bar

