language: c

sudo: false

install:
  - echo hello
  - if [ -f $HOME/tmp/hello.txt ]; then stat $HOME/tmp/hello.txt | grep Modify; fi

script:
  - echo world
  - mkdir -p $HOME/test
  - touch $HOME/test/hello.txt
  - stat $HOME/test/hello.txt | grep Modify;

cache:
  directories:
    - $HOME/test

