language: bash
sudo: required
services:
  - docker

script:
  - docker info
  - df -h
  - ls -lha /mnt
  - cp -r ./baseos/examples/led-blink /tmp/led-blink
  - chmod 0700 /tmp/led-blink
  - docker run -t -v /tmp/led-blink:/app codestand/baseos
  - sudo mount -t tmpfs /tmp
  - ls -lha /tmp
  - cp -r ./baseos/examples/led-blink /tmp/led-blink
  - ls -lha /tmp
  - docker run -t -v /tmp/led-blink:/app codestand/baseos
