language: bash
sudo: required
services:
- docker
- mysql-server
before_install:
- ls /var/run/mysqld
script:
- ls /var/run/mysqld
- mysql -u root -e 'create database hello4;'
- mysql -e 'create database hello3;'
