language: bash
sudo: required
services:
- mysql
script:
- ls /var/run/mysqld
- mysql -uroot -e 'create database hello;';
- mysql -u root -e 'create database hello;';
- mysql -e 'create datbase hello;'
