language: cpp
compiler:
  - gcc
script:
  - wget -O a.deb https://launchpad.net/~serge-hallyn/+archive/crossc/+files/binutils-sparc-linux-gnu_2.23.1-0ubuntu11cross0.3ubuntu1~ppa2_i386.deb
  - sudo dpkg -i a.deb
