language: cpp
compiler:
  - gcc
before_install:
  - git config --global user.email "sh19910711+ynkkowrv0b14@gmail.com"
  - git config --global user.name "Mr. Bot"
  - sudo apt-get update
  - wget http://files.yomogimochi.com/sources/gcc-4.9.0.tar.bz2
# sudo apt-get -yV install gcc-multilib g++-multilib gfortran-multilib
# sudo apt-get -yV install make
# sudo apt-get -yV install patch
# sudo apt-get -yV install build-essential
# sudo apt-get -yV install autoconf
# sudo apt-get -yV install automake
# sudo apt-get -yV install autogen
# sudo apt-get -yV install binutils
# sudo apt-get -yV install bison
# sudo apt-get -yV install ccache
# sudo apt-get -yV install chrpath
# sudo apt-get -yV install dejagnu
# sudo apt-get -yV install expect
# sudo apt-get -yV install flex
# sudo apt-get -yV install gawk
# sudo apt-get -yV install g++-4.6-multilib 
# sudo apt-get -yV install gcc-4.6-multilib 
# sudo apt-get -yV install lib32gcc1 
# sudo apt-get -yV install lib32gomp1 
# sudo apt-get -yV install lib32quadmath0 
# sudo apt-get -yV install lib32stdc++6 
# sudo apt-get -yV install libc6-dev-i386 
# sudo apt-get -yV install libcloog-ppl-dev 
# sudo apt-get -yV install libcloog-ppl0 
# sudo apt-get -yV install libelfg0 
# sudo apt-get -yV install libelfg0-dev 
# sudo apt-get -yV install libmpc-dev 
# sudo apt-get -yV install libtool
# sudo apt-get -yV install openssl
# sudo apt-get -yV install sharutils
# sudo apt-get -yV install libppl0.11-dev
# sudo apt-get -yV install libisl-dev 
install:
  - sudo apt-get -y install g++-multilib gcc-multilib libgmp3-dev libmpfr-dev libmpc-dev
  - tar xf gcc-4.9.0.tar.bz2
  - pushd gcc-4.9.0
  - ./configure 
          --prefix=$HOME/local 
          --with-system-zlib 
          --enable-languages=c,c++ 
          --enable-multilib 
          --disable-bootstrap
  - make -j 2 2>&1 | tee make.log | sed '1~5n; d'
  - make install
  - git clone --single-branch -b tlog git://github.com/sh19910711/test.git repo
  - cp make.log repo/make-`date +"%s"`.log
  - pushd repo
  - git add make-*.log
  - git commit -m 'add make log'
  - git push --quiet https://${GITHUB_TOKEN}@github.com/sh19910711/test.git tlog
  - popd
  - popd
script:
  - ~/local/bin/gcc --version
env:
  - secure: "JR5edl1pvaV1CEePX3D79L3/4gsVYrkZybOjIxagV+IwFU9M80qsDHOr5n2XKZR6wAMjjzcY+J6agnQasgKReBpITpTcA0mBSKL/aNQDMb2yGACQIdEwIooxz8FGd6QQeqAOptQ3U6nK1JWv/2GtjBDiMli4tLykJ7nLrpI3oqk="
