language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - wget http://ftp.gnu.org/gnu/gcc/gcc-4.9.0/gcc-4.9.0.tar.bz2
install:
  - tar xf gcc-4.9.0
  - cd gcc-4.9.0
  - ./configure --prefix=$HOME/local --disable-bootstrap
  - make -j 2
  - make install
script:
  - ~/local/bin/gcc --version
