# Doc: http://docs.travis-ci.com/user/build-configuration/

language: ruby

rvm:
  - "1.9"
  - "2.0"
  - "2.1"

before_install:
  # vim-gtk: to enable client/server feature
  - sudo apt-get install vim vim-gtk
  - vim --version
  - gvim --version

install:
  - scripts/install_social_snippet
  # TODO: set repository host
  - sspm install example-repo
  - bundle install

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake spec

env:
  global:
    - DISPLAY=:99.0

