language: bash

git:
  depth: 1
  submodules: false

sudo: required # to run docker

services:
  - docker

install:
  - ls -lha
  - ls -lha emu-server
  - bash script/convert.bash

script:
  - sudo docker-compose build
