language: node_js

nvm:
  - "0.10"

sudo: false

install:
  - travis_retry npm install -g gulp
  - travis_retry npm install -g bower
  - travis_retry npm install
  - travis_retry bower install

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - gulp test

env:
  global:
    - DISPLAY=:99.0

cache:
  directories:
    - node_modules
    - bower_components
