language: c

sudo: false

install:
  - echo hello
  - if [ -f $HOME/tmp/hello.txt ]; then stat $HOME/tmp/hello.txt | grep Modify; fi

script:
  - echo world
  - mkdir -p $HOME/tmp
  - touch $HOME/tmp/hello.txt
  - stat $HOME/tmp/hello.txt | grep Modify;

cache:
  directories:
    - $HOME/tmp/

