language: c

sudo: false

install:
  - echo hello
  - "[ -f $HOME/tmp/hello.txt ] && stat $HOME/tmp/hello.txt | grep Modify;"

script:
  - echo world
  - mkdir -p $HOME/tmp
  - touch $HOME/tmp/hello.txt
  - stat $HOME/tmp/hello.txt | grep Modify;

cache:
  directories:
    - $HOME/tmp/

