language: objective-c

rvm:
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9"

sudo: false

before_install:
  - git config --global user.email "dummy@localhost"
  - git config --global user.name "This Is Dummyyy"

install:
  - bundle config build.nokogiri --use-system-libraries
  - travis_retry bundle install --jobs 4 --path vendor/bundle
  - bundle exec rake install

script:
  - bundle exec rake spec

