#!/bin/bash

unset BUNDLE_GEMFILE
set -eu

function exec() {
  echo "command: $1"
  $1
}

export SOCIAL_SNIPPET_TMPDIR=`mktemp -d`

exec "pushd $SOCIAL_SNIPPET_TMPDIR" || exit 1
exec 'git clone --single-branch -b feature/ssnip-command git://github.com/social-snippet/social-snippet.git social-snippet'
exec 'cd social-snippet'
exec 'bundle install' || exit 1
exec 'bundle exec rake build' || exit 1
exec 'gem install pkg/social_snippet-*.gem' || exit 1
exec 'popd' || exit 1

exit 0
